// Code generated by a template
using System;
using Mercury.AssertBuilder;
using System.Collections.Generic;

namespace Mercury.AssertBuilder
{
	internal sealed class DataPreAssertBuilder<TSut> : IAssertWithDataCaseBuilder<TSut>
    {
        private readonly Func<TSut> _actFunc;
        private readonly ISuite _suite;

        public DataPreAssertBuilder(Func<TSut> actFunc,
                           ISuite suite)
        {
            _actFunc = actFunc;
            _suite = suite;
        }

        public IPostAssertWithDataCaseBuilder<TSut> Assert(Action<TSut> assertAction)
        {
            return new DataAssertBuilder<TSut>(_actFunc, _suite).Assert(assertAction);
        }

        public IPostAssertWithDataCaseBuilder<TSut> Assert(string assertionTestCaseName,
            Action<TSut> assertAction)
        {
            return new DataAssertBuilder<TSut>(_actFunc, _suite).Assert(assertionTestCaseName,
                assertAction);
        }
    }
}
