// Code generated by a template
using System;
using Mercury.AssertBuilder;
namespace Mercury
{
  public interface IArrangedWithData<out TSut>
  {
     IAssertWithDataCaseBuilder<TPostAct> Act<TPostAct>(Func<TSut, TPostAct> actFunc);
     IArrangedWithData<TSut> With();
  }

  public interface IAssertWithDataCaseBuilder<out TSut>
  {
      IPostAssertWithDataCaseBuilder<TSut> Assert(Action<TSut> assertAction);
      IPostAssertWithDataCaseBuilder<TSut> Assert(string assertionTestCaseName, Action<TSut> assertAction);
  }

  public interface IPostAssertWithDataCaseBuilder<out TSut> : ISpecification,
        IAssertWithDataCaseBuilder<TSut>
  {
  }
}
