// Code generated by a template
using System;
using Mercury.AssertBuilder;
using System.Collections.Generic;

namespace Mercury.AssertBuilder
{
	internal sealed class PreAssertBuilder<TSut, TData> : IAssertCaseBuilder<TSut, TData>
    {
        private readonly Func<TData, TSut> _actFunc;
        private readonly IDataSuite<TData> _dataSuite;

        public PreAssertBuilder(IDataSuite<TData> dataSuite, Func<TData, TSut> actFunc)
        {
            _actFunc = actFunc;
            _dataSuite = dataSuite;
        }

        public IPostAssertCaseBuilder<TSut, TData> Assert(Action<TSut, TData> assertAction)
        {
            return new AssertBuilder<TSut, TData>(_actFunc, _dataSuite).Assert(assertAction);
        }

        public IPostAssertCaseBuilder<TSut, TData> Assert(string assertionTestCaseName,
            Action<TSut, TData> assertAction)
        {
            return new AssertBuilder<TSut, TData>(_actFunc, _dataSuite).Assert(assertionTestCaseName,
                assertAction);
        }
    }
}
