// Code generated by a template
using System;
using Mercury.AssertBuilder;
using System.Collections.Generic;

namespace Mercury.AssertBuilder
{
	internal sealed class PreAssertBuilder<TSut, TData1, TData2> : IAssertCaseBuilder<TSut, TData1, TData2>
    {
        private readonly Func<TData1, TData2, TSut> _actFunc;
        private readonly IDataSuite<Tuple<TData1, TData2>> _dataSuite;

        public PreAssertBuilder(IDataSuite<Tuple<TData1, TData2>> dataSuite, Func<TData1, TData2, TSut> actFunc)
        {
            _actFunc = actFunc;
            _dataSuite = dataSuite;
        }

        public IPostAssertCaseBuilder<TSut, TData1, TData2> Assert(Action<TSut, TData1, TData2> assertAction)
        {
            return new AssertBuilder<TSut, TData1, TData2>(_actFunc, _dataSuite).Assert(assertAction);
        }

        public IPostAssertCaseBuilder<TSut, TData1, TData2> Assert(string assertionTestCaseName,
            Action<TSut, TData1, TData2> assertAction)
        {
            return new AssertBuilder<TSut, TData1, TData2>(_actFunc, _dataSuite).Assert(assertionTestCaseName,
                assertAction);
        }
    }
}
